name: test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: "16.19.0"
          cache: "yarn"
      - run: "yarn install"
      - run: "yarn analyze"
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: "16.19.0"
          cache: "yarn"
      - run: "yarn install"
      - run: "yarn test"
  test_acceptance:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: "16.19.0"
          cache: "yarn"
      - run: "yarn install"
      - uses: cypress-io/github-action@v2
        with:
          command: "yarn ci:test:acc"
